In [8]:
!pip install flair


     |████████████████████████████████| 401 kB 13.7 MB/s 
     |████████████████████████████████| 53 kB 1.6 MB/s 
     |████████████████████████████████| 1.6 MB 55.1 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 788 kB 55.7 MB/s 
     |████████████████████████████████| 46 kB 3.1 MB/s 
     |████████████████████████████████| 48 kB 4.9 MB/s 
     |████████████████████████████████| 1.2 MB 63.6 MB/s 
     |████████████████████████████████| 981 kB 48.2 MB/s 
     |████████████████████████████████| 19.7 MB 1.2 MB/s 
     |████████████████████████████████| 199 kB 52.7 MB/s 
     |████████████████████████████████| 63 kB 1.7 MB/s 
  Created wheel for gdown: filename=gdown-3.12.2-py3-none-any.whl size=9692 sha256=5d03cf5af3d91fbad8d98616aa93c5e96b42b07b7c6f62755e27ce3bbfe08c78
  Stored in directory: /root/.cache/pip/wheels/ba/e0/7e/726e872a53f7358b4b96a9975b04e98113b005cd

In [1]:
!pip install transformers
!pip install torch

     |████████████████████████████████| 4.0 MB 8.8 MB/s 
     |████████████████████████████████| 895 kB 42.0 MB/s 
     |████████████████████████████████| 596 kB 42.3 MB/s 
     |████████████████████████████████| 6.5 MB 47.7 MB/s 
     |████████████████████████████████| 77 kB 2.8 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [13]:
# import wandb
import pandas as pd
import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import DataLoader
from transformers import BertTokenizer, BertModel, BertForMaskedLM
import re
from flair.data import Sentence
from flair.embeddings import BertEmbeddings


PRETRAINED_MODEL_NAME = "bert-base-multilingual-cased" 
file_path = "data.csv"

text = "This article try to explain the result obtain in a teach innovation project which join education and cultural heritage. take advantage of the hold the exhibition ??The Art of Clara Peeters ??( autumn, 2016 ), the first exhibition devote to a woman painter in the Prado Museum, we developped a interdisciplinary projectbased learn with student from Master in Secondary Teacher train, specialize in Social science, of the be? laga University. They have to organize several activity for student from secondary education who have the opportunity of know the role of the woman in the history and the art, other story, other geography, still life painting o the daily life. In this Project, there be apply this methodology: servicelearning, problem base learn, collaborative learn, cooperative learn and flip classroom. This projet would achieve the follow goal: the elimination of prejudice concern the perception of the master as a necessary formality, the enlargement of the practical dimension, the implementation of innovative methodology, the interdisciplinary approach, the teamwork and the knowledge the existence of a ??hide curriculum ??? 2018, Universidad Complutense de Madrid. All right reserve."

#read the data
class load_data():
    def __init__(self, path):
        super(load_data, self).__init__()
        self.path = path

    def data_load(self):
        file = pd.read_csv(self.path)
        abstract = file.loc[:,'Abstract_lemma'].values
        return abstract


class bert_model():
    def __init__(self, text):
        super(bert_model, self).__init__()
        self.text = text

    def bert(self):

        tokenizer = BertTokenizer.from_pretrained(PRETRAINED_MODEL_NAME)
        model = BertModel.from_pretrained(PRETRAINED_MODEL_NAME)
        encoded_inputs = tokenizer(self.text, padding=True, truncation=True, return_tensors="pt")                            
        ids = encoded_inputs['input_ids']
        mask = encoded_inputs['attention_mask']
        output = model(ids, mask)
        final_layer = output.last_hidden_state
        print(final_layer)
        
        
    def word_embedding(self):
        string = ''.join(self.text)
        s = Sentence(self.text)
        bert_embedding = BertEmbeddings()
        bert_embedding.embed(s)
        for token in s:
            print(token.embedding)



In [17]:
from google.colab import drive
drive.mount('/content/drive')
path = "/content/drive/My Drive/dataset/data.csv"
data = load_data(path)
text = data.data_load()
model = bert_model(text[1])
model.word_embedding()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:50: DeprecationWarning: Call to deprecated method __init__. (Use 'TransformerWordEmbeddings' for all transformer-based word embeddings) -- Deprecated since version 0.4.5.
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertFo

tensor([-0.1391,  0.2538, -0.5389,  ..., -0.4767,  1.3827, -0.9987])
tensor([-1.0994,  0.1948, -0.2257,  ...,  0.3568,  0.7565, -0.1836])
tensor([ 0.0521,  0.2693, -0.4582,  ..., -0.8610,  1.3562,  0.2120])
tensor([-0.9308, -0.2944, -0.7477,  ..., -0.4552,  0.6817,  0.0857])
tensor([-0.2278,  0.2282,  0.1193,  ..., -0.3592, -0.1034, -0.2523])
tensor([-0.4827,  0.3503,  0.0153,  ..., -0.9832,  1.3845, -0.4342])
tensor([-0.8440, -0.1176,  0.2153,  ..., -0.9877,  1.3416,  0.3147])
tensor([-0.8693, -0.4426,  0.7813,  ..., -1.3042,  0.9296, -0.2100])
tensor([-0.7882, -0.6301,  0.0555,  ..., -1.6778,  0.3201,  0.8916])
tensor([-0.2539, -0.6022, -0.0806,  ..., -1.8320, -0.2663,  0.5676])
tensor([ 0.2352,  0.3128,  0.4911,  ..., -0.7645,  0.8871,  0.3768])
tensor([ 0.3067,  0.4728,  0.9921,  ..., -1.2887,  0.1811, -0.2376])
tensor([ 0.0492,  0.2367,  0.8794,  ..., -1.1637,  0.5889,  0.1639])
tensor([-0.3282,  0.5400,  1.1334,  ..., -0.7951, -0.1373,  0.8047])
tensor([-0.2863, -0.3721,  0.2555,